vpc_cidr              = "10.21.0.0/16"
subnet_newbits        = 8
region                = "us-east-1"
az_count              = 3
nat_availability_mode = "zonal"
environment           = "nonprod"
project_name          = "platform"
project_owner         = "DevOps Team"
default_sg_required   = true
cluster_name          = "platform-nonprod"
cluster_version       = "1.34"
node_group_scaling = {
  desired_size = 2
  max_size     = 3
  min_size     = 1
}
node_instance_types                = ["t3.medium"]
node_disk_size                     = 100
eks_mode                           = "standard"
auth_mode                          = "API_AND_CONFIG_MAP"
create_lbc_role                    = true
create_external_dns_role           = false
create_secrets_store_provider_role = false
secrets_manager_secret_arns        = []
secrets_manager_kms_key_arns       = []
ami_id                             = "ami-0b6d9d3d33ba97d99"
instance_type                      = "t2.micro"
az                                 = "us-east-1a"
enable_public_ip                   = true
root_volume_specs = {
  delete_on_termination = true
  encrypted             = true
  size                  = 50
  type                  = "gp3"
}
data_volume_specs = {}