name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed.outputs.dirs }}
      has-changes: ${{ steps.changed.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changed
        uses: pratik-khot/github-common-workflows/.github/actions/changed-terraform-dirs@v1.2.0

  checkov-scan:
    needs: 
      - detect-changes
    if: needs.detect-changes.outputs.has-changes == 'true'
    uses: pratik-khot/github-common-workflows/.github/workflows/checkov-scan.yml@v1.2.0
    with:
      scan-roots: ${{ needs.detect-changes.outputs.dirs }}

  terraform-plan:
    needs: 
      - detect-changes
      - checkov-scan

    if: needs.detect-changes.outputs.has-changes == 'true'
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-plan.yml@v1.2.0
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-roots: ${{ needs.detect-changes.outputs.dirs }}
    secrets: inherit
  
  terraform-apply:
    needs: 
      - terraform-plan
      - detect-changes
      - checkov-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.detect-changes.outputs.has-changes == 'true'
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-apply.yml@v1.2.0
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-roots: ${{ needs.detect-changes.outputs.dirs }}
    secrets: inherit