name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  gitleaks-scan:
    uses: pratik-khot/github-common-workflows/.github/workflows/gitleaks-scan.yml@v1.1.1
  checkov-scan:
    uses: pratik-khot/github-common-workflows/.github/workflows/checkov-scan.yml@v1.1.1
  terraform-plan:
    needs: 
      - checkov-scan
      - gitleaks-scan
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-plan.yml@v1.1.1
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-version: ${{ vars.terraform_version }}
    secrets: inherit
  
  terraform-apply:
    needs: 
      - checkov-scan
      - gitleaks-scan
      - terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-apply.yml@v1.1.1
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-version: ${{ vars.terraform_version }}
      environment: dev
    secrets: inherit