name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  security-scan:
    uses: pratik-khot/github-common-workflows/.github/workflows/security-scan.yml@v1
  terraform-plan:
    needs: security-scan
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-plan.yml@v1
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-version: ${{ vars.terraform_version }}
    secrets: inherit
  
  terraform-apply:
    needs: 
      - security-scan
      - terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: pratik-khot/github-common-workflows/.github/workflows/terraform-apply.yml@v1
    with:
      aws-region: ${{ vars.aws_region }}
      terraform-version: ${{ vars.terraform_version }}
    secrets: inherit